name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeterminateSystems/nix-installer-action@v2
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: actions/cache@v3
        id: nix-cache
        with:
          path: /nix/store
          key: ${{ runner.os }}-nix-store-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-nix-store-
      - name: Build
        run: |
          nix build #.
          ./result/bin/db_sync --version
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./result/bin/db_sync
          asset_name: db_sync_${{ github.ref_name }}_linux
          asset_content_type: application/octet-stream
      - uses: actions/cache@v3
        if: steps.nix-cache.outputs.cache-hit != 'true'
        with:
          path: /nix/store
          key: ${{ runner.os }}-nix-store-${{ hashFiles('**/Cargo.lock') }}
