name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeterminateSystems/nix-installer-action@v2
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: actions/cache@v3
        id: nix-cache
        with:
          path: /nix/store
          key: ${{ runner.os }}-nix-store-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-nix-store-
      - name: Build
        run: |
          nix build #.
          ./result/bin/db_sync --version
      - uses: actions/cache@v3
        if: steps.nix-cache.outputs.cache-hit != 'true'
        with:
          path: /nix/store
          key: ${{ runner.os }}-nix-store-${{ hashFiles('**/Cargo.lock') }}
      - name: Release
        uses: softprops/action-gh-release@v2
