name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeterminateSystems/nix-installer-action@v2
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build
        run: |
          nix-build . -A db_sync
          ./result/bin/db_sync --version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./result/bin/db_sync
          asset_name: db_sync_${{ github.ref_name }}_linux
          asset_content_type: application/octet-stream
